//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/_Dev/Leo/InputManager/InputPlayerLeo.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Leo
{
    public partial class @InputPlayerLeo: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @InputPlayerLeo()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputPlayerLeo"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""05529e56-6ebc-4cc6-ae73-d71984534bf8"",
            ""actions"": [
                {
                    ""name"": ""ChangeGravity"",
                    ""type"": ""Button"",
                    ""id"": ""23cdac13-e3a2-4ed9-b29c-03878bf084c9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Teleport"",
                    ""type"": ""Button"",
                    ""id"": ""72133826-4177-41ea-9d31-8cc955bc8698"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Float"",
                    ""type"": ""Button"",
                    ""id"": ""18b458bb-26d3-4888-80e1-ea7b8f8a7a1e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fd0db487-fb59-4233-bef0-255e69ec0685"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeGravity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8dd895e3-051b-4253-96b0-23b3fd3e4ea1"",
                    ""path"": ""<Touchscreen>/touch*/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeGravity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf3d40b2-def5-445e-a02b-479d87d62b23"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Teleport"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4fbe59d-f20b-4063-ac21-359323703de2"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Float"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Gameplay
            m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
            m_Gameplay_ChangeGravity = m_Gameplay.FindAction("ChangeGravity", throwIfNotFound: true);
            m_Gameplay_Teleport = m_Gameplay.FindAction("Teleport", throwIfNotFound: true);
            m_Gameplay_Float = m_Gameplay.FindAction("Float", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Gameplay
        private readonly InputActionMap m_Gameplay;
        private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
        private readonly InputAction m_Gameplay_ChangeGravity;
        private readonly InputAction m_Gameplay_Teleport;
        private readonly InputAction m_Gameplay_Float;
        public struct GameplayActions
        {
            private @InputPlayerLeo m_Wrapper;
            public GameplayActions(@InputPlayerLeo wrapper) { m_Wrapper = wrapper; }
            public InputAction @ChangeGravity => m_Wrapper.m_Gameplay_ChangeGravity;
            public InputAction @Teleport => m_Wrapper.m_Gameplay_Teleport;
            public InputAction @Float => m_Wrapper.m_Gameplay_Float;
            public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
            public void AddCallbacks(IGameplayActions instance)
            {
                if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
                @ChangeGravity.started += instance.OnChangeGravity;
                @ChangeGravity.performed += instance.OnChangeGravity;
                @ChangeGravity.canceled += instance.OnChangeGravity;
                @Teleport.started += instance.OnTeleport;
                @Teleport.performed += instance.OnTeleport;
                @Teleport.canceled += instance.OnTeleport;
                @Float.started += instance.OnFloat;
                @Float.performed += instance.OnFloat;
                @Float.canceled += instance.OnFloat;
            }

            private void UnregisterCallbacks(IGameplayActions instance)
            {
                @ChangeGravity.started -= instance.OnChangeGravity;
                @ChangeGravity.performed -= instance.OnChangeGravity;
                @ChangeGravity.canceled -= instance.OnChangeGravity;
                @Teleport.started -= instance.OnTeleport;
                @Teleport.performed -= instance.OnTeleport;
                @Teleport.canceled -= instance.OnTeleport;
                @Float.started -= instance.OnFloat;
                @Float.performed -= instance.OnFloat;
                @Float.canceled -= instance.OnFloat;
            }

            public void RemoveCallbacks(IGameplayActions instance)
            {
                if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IGameplayActions instance)
            {
                foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public GameplayActions @Gameplay => new GameplayActions(this);
        public interface IGameplayActions
        {
            void OnChangeGravity(InputAction.CallbackContext context);
            void OnTeleport(InputAction.CallbackContext context);
            void OnFloat(InputAction.CallbackContext context);
        }
    }
}
